### ISSUE TITLE
Group by faconne fails

### ISSUE THREAD

**Issue by viweis** [turtlegrammar/faconne#6]
Some issues about Clojure faconne confuse me. 

For example,
```
(faconne.core/transform [{:B 1} {:B 2}]
                        [{:B B}]
                        {:B [B]})
=> {:B [1 2]}
```

This is good for me. But something gets worse when there are more arrays in data.
```
(faconne.core/transform [{:A [{:B 1} {:B 2}],:C 5} {:A [{:B 3} {:B 4}],:C 6}]
                        [{:A [{:B B}],:C C}]
                        [{:A {:B [B]},:C C}])


=> [{:A {:B [1]}, :C 5} {:A {:B [2]}, :C 5} {:A {:B [3]}, :C 6} {:A {:B [4]}, :C 6}]
```
But what I want is `[{:A {:B [1 2]}, :C 5}  {:A {:B [3 4]}, :C 6}]`.  

I want to realize it only by faconne. Can you help me?

**Comment by viweis** [comment]
Even I set domain the same as range, the result is different from data source.
```
(faconne.core/transform [{:A [{:B 1} {:B 2}],:C 5} {:A [{:B 3} {:B 4}],:C 6}]
                        [{:A [{:B B}],:C C}]
                        [{:A [{:B B}],:C C}])
=> [{:A [{:B 1}], :C 5} {:A [{:B 2}], :C 5} {:A [{:B 3}], :C 6} {:A [{:B 4}], :C 6}]

**Comment by turtlegrammar** [comment]
Thanks for using faconne and sorry for the delayed response (I was away from my computer for a couple days). You can achieve the transform like this: 

```clj
(-> [{:A [{:B 1} {:B 2}],:C 5} {:A [{:B 3} {:B 4}],:C 6}]
    ;; group b values by c values
    (faconne.core/transform [{:A [{:B b}] :C c}] {c [b]})
    ;; transform the grouping to an array of records
    (faconne.core/transform {c bs} [{:A {:B bs} :C c}]))

;; => [{:A {:B [1 2]}, :C 5} {:A {:B [3 4]}, :C 6}]
```

In the examples you've provided, faconne is working as intended, and what follows is a more in depth explanation of why it works like that.

`faconne.core/transform` has two phases:
1. Traversing nested maps, array, and sets like a tree (shape is described by second argument to `transform`, like `[{:A [{:B b}] :C c}]` ), and creating values (specified by third argument to `transform`, like `[{:A {:B [B]},:C C}]`) at each leaf in the tree.
2. Deep merging the values created at each leaf to return a single result.

For the input `[{:A {:B [1]}, :C 5} {:A {:B [2]}, :C 5} {:A {:B [3]}, :C 6} {:A {:B [4]}, :C 6}]`, there are four leaves, so faconne creates these four values, one at each leaf:
```clj
[{:A {:B [1]}, :C 5}]
[{:A {:B [2]}, :C 5}]
[{:A {:B [3]}, :C 6}]
[{:A {:B [4]}, :C 6}]
```

After faconne creates values at each leaf in the tree, it deep merges them to get the result. When it deep merges maps, it recursively deep merges values with shared keys. When it merges arrays or sets, it concatenates them, and the recursion stops there. So, this is why the result of the transformation isn't doing the grouping you'd like: grouping can only happen with maps. Sadly, there's no other general way to merge arrays and sets. For example, would faconne merge items with the same `:A` values, `(comp :B :A)` values, `:C` values, or some combination?

You can still get the result you want, but you have to achieve the grouping by first building a map, then transforming the map to the array. In the example at the very top, the first transform is 
```clj
(faconne.core/transform [{:A [{:B b}] :C c}] {c [b]})
```
the values at the leaves will be:
```clj
{5 [1]}
{5 [2]}
{6 [3]}
{6 [4]}
```
when faconne deep merges `{5 [1]}` and `{5 [2]}`, it sees a key conflict, so it recursively merges `[1]` and `[2]` giving `{5 [1 2]}`. Ultimately the first transform in the `->` expression gives us:
```clj
{5 [1 2], 6 [3 4]}
```

when we traverse the tree described by the second transform `{c bs}`, we have two leaves:
```
c=5, bs=[1 2]
c=6, bs=[3 4]
```

so we create these values at the leaves:
```clj
[{:A {:B [1 2]}, :C 5}] 
[{:A {:B [3 4]}, :C 6}]
```

and when we deep merge, we concatenate the arrays to get the desired result.

I'll add an explanation like this to the readme to clarify how `transform` works.

**Comment by viweis** [comment]
Thank you so much.

Maybe I didn't clearly clarify my confuse.  In fact, I want to realize the transformation between jsons. I want to remain the array structure. 

If I change my exmple to `[{:A [{:B 1} {:B 2}],:C 5} {:A [{:B 3} {:B 4}],:C 5}]`, but I still want the result is
 `[ [{:A {:B [1 2]}, :C 5}] 
 [{:A {:B [3 4]}, :C 5}]]`

I know I can realize this by groupping by B first, merge then. But I think you should have understand my issue. I want to keep the json structure is right, especially the array part. 

In fact, I read your clojure code these days. In a complex json, for example,  multi-nest and multi-array，
```
{:A [{:D [{:F 11 }  {:F  12}]  :E 1}    {:D [{:F 13}   {:F 14}] :E 3}]}
``` 

I want to keep the main structure    `{:A [{[]}   {[]}]}`, and extract some keys. Your code maybe is not enough. I try to write a clojure project to realize the transformation between jsons. Just like NiFi jolt or jsonpath. Can you give me some advice?

**Comment by turtlegrammar** [comment]
If you want
```clj
[{:A [{:B 1} {:B 2}],:C 5} {:A [{:B 3} {:B 4}],:C 5}]
```
to
```clj
[ [{:A {:B [1 2]}, :C 5}] [{:A {:B [3 4]}, :C 5}] ]
```
you can do:

```clj
(-> [{:A [{:B 1} {:B 2}],:C 5} {:A [{:B 3} {:B 4}],:C 5}]
    (faconne.core/transform [{:A bs :C c}] [[{:A {:B (mapv :B bs)} :C c}]]))
```

If you want the output to be
```clj
[{:A {:B [1 2]}, :C 5} {:A {:B [3 4]}, :C 5}]
```

you could do 

```clj
(-> [{:A [{:B 1} {:B 2}],:C 5} {:A [{:B 3} {:B 4}],:C 5}]
    (faconne.core/transform [{:A bs :C c}] [{:A {:B (mapv :B bs)} :C c}]))
```

The key here is to tell faconne to treat the whole array of :B's as one leaf instead of having a leaf for each item in the array. And faconne lets you put arbitrary clojure code in the transform, so you can do `(mapv :B bs)`.

Does that help?

**Comment by viweis** [comment]
How about this example
```
(-> {:A [{:A1 1} {:A1 2}]
     :B 3
     :C [{:C1 4 :C2 5} {:C1 1 :C2 2}]}
    (faconne.core/transform {:A a, :B b, :C [{:C1 c1}]}
                            {:A a, :B b, :C [{:C1 c1}]})
    )
=> {:A [{:A1 1} {:A1 2} {:A1 1} {:A1 2}], :B 3, :C [{:C1 4} {:C1 1}]}
```

I want the output to be
```
=> {:A [{:A1 1} {:A1 2}], :B 3, :C [{:C1 4} {:C1 1}]}
```

I know I can do it by 
```
(-> {:A [{:A1 1} {:A1 2}]
     :B 3
     :C [{:C1 4 :C2 5} {:C1 1 :C2 2}]}
    (faconne.core/transform {:A a, :B b, :C c}
                            {:A a, :B b, :C (mapv #(select-keys % [:C1]) c)})
    )
=> {:A [{:A1 1} {:A1 2}], :B 3, :C [{:C1 4} {:C1 1}]}
```

The issue is I think we need to treat the value of A and C seperately in a map. We should not change the value of A due to C.

**Comment by turtlegrammar** [comment]
In that case, I don't think I would use faconne. Ultimately faconne is an abstraction over the following process: traverse a tree, create a monoid (basically, a data structure that you can merge) at each leaf, deep merge all the monoids into a single result. In this example, I wouldn't think about traversing a tree. Instead, we're updating the value of a key in the map, so I would write:

```clj
(-> {:A [{:A1 1} {:A1 2}]
     :B 3
     :C [{:C1 4 :C2 5} {:C1 1 :C2 2}]}
    (update :C (partial mapv #(select-keys % [:C1]))))
```

In medium-sized or big projects, I usually define a lot of reusable helper functions for common sequence operations, so actually I'd probably write:

```clj
(defn update-vector 
  [m k f]
  (update m k (partial mapv f)))

(-> {:A [{:A1 1} {:A1 2}]
     :B 3
     :C [{:C1 4 :C2 5} {:C1 1 :C2 2}]}
    (update-vector :C #(select-keys % [:C1])))
```

In practice, in my Clojure projects, I use faconne somewhat frequently, but I prefer clojure.core's sequence functions (map, filter, reduce, update, etc.) _if_ there's an elegant way to write it with those. With deeply nested structures that require complex transformations, there's often no elegant solution without faconne (in my opinion). But there's a lot of simple transformations where clojure.core is elegant.
